// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRZScnRKPPh9vIj3w9dgRQvzimIdLqnA',
    appId: '1:631680147171:web:7598208a6026161746afd6',
    messagingSenderId: '631680147171',
    projectId: 'mct-app-5bc26',
    authDomain: 'mct-app-5bc26.firebaseapp.com',
    storageBucket: 'mct-app-5bc26.firebasestorage.app',
    measurementId: 'G-MELREF816S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8a4AIPgh9g6wBunRBghpr-a897WaWv0I',
    appId: '1:631680147171:android:94e65b9293d946ad46afd6',
    messagingSenderId: '631680147171',
    projectId: 'mct-app-5bc26',
    storageBucket: 'mct-app-5bc26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQ7EVPmWLoHrMQUjylBC0T8ftm1wnF_Y',
    appId: '1:631680147171:ios:a308bcc524c7f13246afd6',
    messagingSenderId: '631680147171',
    projectId: 'mct-app-5bc26',
    storageBucket: 'mct-app-5bc26.firebasestorage.app',
    iosBundleId: 'com.example.mctPrayerBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQ7EVPmWLoHrMQUjylBC0T8ftm1wnF_Y',
    appId: '1:631680147171:ios:a308bcc524c7f13246afd6',
    messagingSenderId: '631680147171',
    projectId: 'mct-app-5bc26',
    storageBucket: 'mct-app-5bc26.firebasestorage.app',
    iosBundleId: 'com.example.mctPrayerBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrRZScnRKPPh9vIj3w9dgRQvzimIdLqnA',
    appId: '1:631680147171:web:1ac6165e028bd54d46afd6',
    messagingSenderId: '631680147171',
    projectId: 'mct-app-5bc26',
    authDomain: 'mct-app-5bc26.firebaseapp.com',
    storageBucket: 'mct-app-5bc26.firebasestorage.app',
    measurementId: 'G-QZMQNPBD48',
  );

}