// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWELNOroUEDJkP0kQFbUqzgCOcViddDFI',
    appId: '1:421331551496:web:ac0240a0504df7f81dd8bd',
    messagingSenderId: '421331551496',
    projectId: 'mct-app-5698e',
    authDomain: 'mct-app-5698e.firebaseapp.com',
    databaseURL: 'https://mct-app-5698e-default-rtdb.firebaseio.com',
    storageBucket: 'mct-app-5698e.firebasestorage.app',
    measurementId: 'G-KBDDHVJ1K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWOrN8iV0UyVG6_y3t2BOQQFdDmU8H5s',
    appId: '1:421331551496:android:e521d6acf54ccbd11dd8bd',
    messagingSenderId: '421331551496',
    projectId: 'mct-app-5698e',
    databaseURL: 'https://mct-app-5698e-default-rtdb.firebaseio.com',
    storageBucket: 'mct-app-5698e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqE8WRpQWEKQajsmNUw1GRNjkVQnkSWTU',
    appId: '1:421331551496:ios:85e2f1eced6c8fa61dd8bd',
    messagingSenderId: '421331551496',
    projectId: 'mct-app-5698e',
    databaseURL: 'https://mct-app-5698e-default-rtdb.firebaseio.com',
    storageBucket: 'mct-app-5698e.firebasestorage.app',
    iosBundleId: 'com.example.mctPrayerBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqE8WRpQWEKQajsmNUw1GRNjkVQnkSWTU',
    appId: '1:421331551496:ios:85e2f1eced6c8fa61dd8bd',
    messagingSenderId: '421331551496',
    projectId: 'mct-app-5698e',
    databaseURL: 'https://mct-app-5698e-default-rtdb.firebaseio.com',
    storageBucket: 'mct-app-5698e.firebasestorage.app',
    iosBundleId: 'com.example.mctPrayerBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWELNOroUEDJkP0kQFbUqzgCOcViddDFI',
    appId: '1:421331551496:web:c42182ae5ad700ab1dd8bd',
    messagingSenderId: '421331551496',
    projectId: 'mct-app-5698e',
    authDomain: 'mct-app-5698e.firebaseapp.com',
    databaseURL: 'https://mct-app-5698e-default-rtdb.firebaseio.com',
    storageBucket: 'mct-app-5698e.firebasestorage.app',
    measurementId: 'G-FLXMJWMW8R',
  );
}
